# Generated by Django 4.2.2 on 2023-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('Jewelry', 'Jewelry'), ('Electronics', 'Electronics'), ('Clothes', 'Clothers'), ('Others', 'Others')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='productimages')),
                ('secure_key', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=100)),
                ('sign_email', models.EmailField(max_length=100, unique=True)),
                ('sign_password', models.CharField(max_length=100)),
                ('sign_time', models.DateTimeField(auto_now=True)),
                ('secure_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
    ]
